name = "advent_of_code_2023"
description = "advent of code 2023 in Ada"
version = "0.1.0-dev"

authors = ["David Joseph Haley"]
maintainers = ["David Joseph Haley <david.haley@bigpond.com>"]
maintainers-logins = ["David-Haley"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = ""
tags = ["aoc", "2023", "ada"]

executables = ["advent_of_code_2023"]
